# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/f2663/Desktop/385final/final/final.runs/synth_1/mb_usb_hdmi_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/f2663/Desktop/385final/final/final.cache/wt [current_project]
set_property parent.project_path C:/Users/f2663/Desktop/385final/final/final.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/f2663/Desktop/ece385/Lab6/RD_hdmi_ip2020/hdmi_tx_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/f2663/Desktop/385final/final/final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/background_1/background_1.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/player_1/player_1.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/player_2/player_2.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/walk/walk.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/player_1_back/player_1_back.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/run/run.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/runf/runf.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/walk2/walk2.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/run2/run2.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/runf2/runf2.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/player_2_back/player_2_back.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/walk1_back/walk1_back.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/run1_back/run1_back.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/runf1_back/runf1_back.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/walk2_back/walk2_back.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/run2_back/run2_back.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/runf2_back/runf2_back.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/jump1_1/jump1_1.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/jump1_2/jump1_2.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/jump1_3/jump1_3.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/jump2_1/jump2_1.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/jump2_2/jump2_2.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/jump2_3/jump2_3.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/attack1/attack1.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/attack2/attack2.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/jumpb1_1/jumpb1_1.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/jumpb2_1/jumpb2_1.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/attackb1/attackb1.COE
add_files C:/Users/f2663/Desktop/385final/Image_to_COE/attackb2/attackb2.COE
add_files c:/Users/f2663/Desktop/385final/Image_to_COE/ball/ball.COE
read_verilog C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/new/game_data.sv
set_property file_type "Verilog Header" [get_files C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/new/game_data.sv]
read_verilog -library xil_defaultlib -sv {
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/lab6/lab6_2_provided/design_source/Color_Mapper.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/lab6/lab6_2_provided/design_source/VGA_controller.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/attack1/attack1_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/attack1/attack1_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/attack2/attack2_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/attack2/attack2_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/attackb1/attackb1_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/attackb1/attackb1_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/attackb2/attackb2_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/attackb2/attackb2_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/background_1/background_1_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/background_1/background_1_palette.sv
  C:/Users/f2663/Desktop/ball.sv
  C:/Users/f2663/Desktop/385final/Image_to_COE/ball/ball_example.sv
  C:/Users/f2663/Desktop/385final/Image_to_COE/ball/ball_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/lab7_1_provided_fa24/font_rom.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/lab6/lab6_2_provided/design_source/hex_driver.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jump1_1/jump1_1_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jump1_1/jump1_1_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jump1_2/jump1_2_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jump1_2/jump1_2_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jump1_3/jump1_3_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jump1_3/jump1_3_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jump2_1/jump2_1_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jump2_1/jump2_1_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jump2_2/jump2_2_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jump2_2/jump2_2_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jump2_3/jump2_3_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jump2_3/jump2_3_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jumpb1_1/jumpb1_1_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jumpb1_1/jumpb1_1_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jumpb2_1/jumpb2_1_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/jumpb2_1/jumpb2_1_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Desktop/player.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/player_1_back/player_1_back_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/player_1_back/player_1_back_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/player_1/player_1_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/player_1/player_1_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/player_2_back/player_2_back_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/player_2_back/player_2_back_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/player_2/player_2_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/player_2/player_2_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/run1_back/run1_back_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/run1_back/run1_back_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/run2_back/run2_back_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/run2_back/run2_back_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/run2/run2_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/run2/run2_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/run/run_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/run/run_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/runf1_back/runf1_back_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/runf1_back/runf1_back_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/runf2_back/runf2_back_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/runf2_back/runf2_back_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/runf2/runf2_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/runf2/runf2_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/runf/runf_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/runf/runf_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/new/timer.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/walk1_back/walk1_back_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/walk1_back/walk1_back_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/walk2_back/walk2_back_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/Image_to_COE/walk2_back/walk2_back_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/walk2/walk2_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/walk2/walk2_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/walk/walk_example.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/walk/walk_palette.sv
  C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/imports/lab6/lab6_2_provided/design_source/mb_usb_hdmi_top.sv
}
add_files C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/bd/mb_usb/mb_usb.bd
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_0/mb_usb_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_0/mb_usb_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_0/mb_usb_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_dlmb_v10_0/mb_usb_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_ilmb_v10_0/mb_usb_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_dlmb_bram_if_cntlr_0/mb_usb_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_ilmb_bram_if_cntlr_0/mb_usb_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_lmb_bram_0/mb_usb_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_xbar_0/mb_usb_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_axi_intc_0/mb_usb_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_axi_intc_0/mb_usb_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_axi_intc_0/mb_usb_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_mdm_1_0/mb_usb_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_mdm_1_0/mb_usb_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_clk_wiz_1_0/mb_usb_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_clk_wiz_1_0/mb_usb_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_clk_wiz_1_0/mb_usb_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_rst_clk_wiz_1_100M_0/mb_usb_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_rst_clk_wiz_1_100M_0/mb_usb_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_rst_clk_wiz_1_100M_0/mb_usb_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_rst_0/mb_usb_gpio_usb_rst_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_rst_0/mb_usb_gpio_usb_rst_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_rst_0/mb_usb_gpio_usb_rst_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_int_0/mb_usb_gpio_usb_int_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_int_0/mb_usb_gpio_usb_int_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_int_0/mb_usb_gpio_usb_int_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_keycode_0/mb_usb_gpio_usb_keycode_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_keycode_0/mb_usb_gpio_usb_keycode_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_keycode_0/mb_usb_gpio_usb_keycode_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_timer_usb_axi_0/mb_usb_timer_usb_axi_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_timer_usb_axi_0/mb_usb_timer_usb_axi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/mb_usb_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_0/data/mb_bootloop_le.elf]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/background_rom/background_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/background_rom/background_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/player1_rom/player1_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/player1_rom/player1_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/player_2_rom/player_2_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/player_2_rom/player_2_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/walk_rom/walk_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/walk_rom/walk_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/back_rom/back_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/back_rom/back_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/run_rom/run_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/run_rom/run_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/runf_rom/runf_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/runf_rom/runf_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/walk2_rom/walk2_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/walk2_rom/walk2_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/run2_rom/run2_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/run2_rom/run2_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/runf2_rom/runf2_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/runf2_rom/runf2_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/player_2_back_rom/player_2_back_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/player_2_back_rom/player_2_back_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/walk1_back_rom/walk1_back_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/walk1_back_rom/walk1_back_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/run1_back_rom/run1_back_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/run1_back_rom/run1_back_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/runf1_back_rom/runf1_back_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/runf1_back_rom/runf1_back_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/walk2_back_rom/walk2_back_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/walk2_back_rom/walk2_back_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/run2_back_rom/run2_back_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/run2_back_rom/run2_back_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/runf2_back_rom/runf2_back_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/runf2_back_rom/runf2_back_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/jump1_1_rom/jump1_1_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/jump1_1_rom/jump1_1_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/jump1_2_rom/jump1_2_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/jump1_2_rom/jump1_2_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/jump1_3_rom/jump1_3_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/jump1_3_rom/jump1_3_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/jump2_1_rom/jump2_1_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/jump2_1_rom/jump2_1_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/jump2_2_rom/jump2_2_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/jump2_2_rom/jump2_2_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/jump2_3_rom/jump2_3_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/jump2_3_rom/jump2_3_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/attack1_rom/attack1_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/attack1_rom/attack1_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/attack2_rom/attack2_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/attack2_rom/attack2_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/jumpb1_1_rom/jumpb1_1_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/jumpb1_1_rom/jumpb1_1_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/jumpb2_1_rom/jumpb2_1_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/jumpb2_1_rom/jumpb2_1_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/attackb1_rom/attackb1_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/attackb1_rom/attackb1_rom_ooc.xdc]

read_ip -quiet C:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/attackb2_rom/attackb2_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/attackb2_rom/attackb2_rom_ooc.xdc]

read_ip -quiet c:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/ball_rom/ball_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/ball_rom/ball_rom_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/f2663/Desktop/385final/final/final.srcs/constrs_1/imports/lab6/lab6_1_provided_fa_24/lab6_1_provided/pin_assignment/mb_intro_top.xdc
set_property used_in_implementation false [get_files C:/Users/f2663/Desktop/385final/final/final.srcs/constrs_1/imports/lab6/lab6_1_provided_fa_24/lab6_1_provided/pin_assignment/mb_intro_top.xdc]

read_xdc C:/Users/f2663/Desktop/385final/final/final.srcs/constrs_1/imports/lab6/lab6_2_provided/pin_assignment/mb_usb_hdmi_top.xdc
set_property used_in_implementation false [get_files C:/Users/f2663/Desktop/385final/final/final.srcs/constrs_1/imports/lab6/lab6_2_provided/pin_assignment/mb_usb_hdmi_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/f2663/Desktop/385final/final/final.srcs/utils_1/imports/synth_1/mb_intro_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mb_usb_hdmi_top -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mb_usb_hdmi_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mb_usb_hdmi_top_utilization_synth.rpt -pb mb_usb_hdmi_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
