# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/attack2_rom/attack2_rom.xci
# IP: The module: 'attack2_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/attack2_rom/attack2_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'attack2_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/f2663/Desktop/385final/final/final.srcs/sources_1/ip/attack2_rom/attack2_rom.xci
# IP: The module: 'attack2_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/f2663/Desktop/385final/final/final.gen/sources_1/ip/attack2_rom/attack2_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'attack2_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
